import bannerAsset from './banner_default.jpg';
import ads1Asset from './ads-1.jpg';
import ads2Asset from './ads-2.jpg';
import ads3Asset from './ads-3.jpg';
import ads4Asset from './ads-4.jpg';
import ads5Asset from './ads-5.jpg';
import hotAsset from './tag_vip.png';
import bannerOhdidiAsset from './banner_ohdidi.webp';
import badinhImgAsset from './ba-dinh.jpg';
import dongdaImgAsset from './dong-da.jpg';
import tayhoImgAsset from './tay-ho.jpg';
import thanhxuanImgAsset from './thanh-xuan.jpg';
import tuliemImgAsset from './tu-liem.jpg';
import longbienImgAsset from './long-bien.jpg';
import bannerUserAsset from './banner_app_user.jpg';
import logoAsset from './logo.png';
import bgAuthAsset from './bg_auth.jpg';
import imgAuthAsset from './img_auth.png';
import coinAsset from './icon_coin.svg';
import adminLogoAsset from './default-admin.jpg';
import mailAsset from './icon_mail.svg';
import messAsset from './icon_mess.svg';
import phoneAsset from './icon_phone.svg';
import zaloAsset from './icon_zalo.svg';

type ImportedAsset = string | { src: string };

const resolveAssetUrl = (asset: ImportedAsset): string =>
    typeof asset === 'string' ? asset : asset.src;

const {
    banner,
    ads1,
    ads2,
    ads3,
    ads4,
    ads5,
    hot,
    banner_ohdidi,
    badinh_img,
    dongda_img,
    tayho_img,
    thanhxuan_img,
    tuliem_img,
    longbien_img,
    banner_user,
    logo,
    bg_auth,
    img_auth,
    coin,
    admin_logo,
    mail,
    mess,
    phone,
    zalo,
} = {
    banner: resolveAssetUrl(bannerAsset),
    ads1: resolveAssetUrl(ads1Asset),
    ads2: resolveAssetUrl(ads2Asset),
    ads3: resolveAssetUrl(ads3Asset),
    ads4: resolveAssetUrl(ads4Asset),
    ads5: resolveAssetUrl(ads5Asset),
    hot: resolveAssetUrl(hotAsset),
    banner_ohdidi: resolveAssetUrl(bannerOhdidiAsset),
    badinh_img: resolveAssetUrl(badinhImgAsset),
    dongda_img: resolveAssetUrl(dongdaImgAsset),
    tayho_img: resolveAssetUrl(tayhoImgAsset),
    thanhxuan_img: resolveAssetUrl(thanhxuanImgAsset),
    tuliem_img: resolveAssetUrl(tuliemImgAsset),
    longbien_img: resolveAssetUrl(longbienImgAsset),
    banner_user: resolveAssetUrl(bannerUserAsset),
    logo: resolveAssetUrl(logoAsset),
    bg_auth: resolveAssetUrl(bgAuthAsset),
    img_auth: resolveAssetUrl(imgAuthAsset),
    coin: resolveAssetUrl(coinAsset),
    admin_logo: resolveAssetUrl(adminLogoAsset),
    mail: resolveAssetUrl(mailAsset),
    mess: resolveAssetUrl(messAsset),
    phone: resolveAssetUrl(phoneAsset),
    zalo: resolveAssetUrl(zaloAsset),
};

export const mockHostelData = [
    {
        id: 1,
        image: 'https://tromoi.com/uploads/static/phong_tro_hcm/Quan_12/379%20le%20thi%20rieng/379_le_thi_rieng_9.jpg',
        title: 'Nhà trọ 245 Định Công, Định Công, Hoàng Mai, Hà Nội',
        price: '4,5 triệu/tháng',
        type: 'Nhà trọ, phòng trọ',
        area: '90 m²',
        location: 'Hoàng Mai, Thành phố Hà Nội',
        isFavorite: false,
        isHot: true,
    },
    {
        id: 2,
        image: 'https://tromoi.com/uploads/static/phong_tro_hcm/Quan_12/379%20le%20thi%20rieng/379_le_thi_rieng_10.jpg',
        title: 'Phòng trọ 123 Nguyễn Văn Cừ, Long Biên, Hà Nội',
        price: '3,2 triệu/tháng',
        type: 'Phòng trọ',
        area: '45 m²',
        location: 'Long Biên, Thành phố Hà Nội',
        isFavorite: true,
        isHot: true,
    },
    {
        id: 3,
        image: 'https://tromoi.com/uploads/static/phong_tro_hcm/Quan_12/379%20le%20thi%20rieng/379_le_thi_rieng_11.jpg',
        title: 'Nhà nguyên căn 456 Lê Văn Lương, Thanh Xuân, Hà Nội',
        price: '8,5 triệu/tháng',
        type: 'Nhà nguyên căn',
        area: '120 m²',
        location: 'Thanh Xuân, Thành phố Hà Nội',
        isFavorite: false,
        isHot: true,
    },
    {
        id: 4,
        image: 'https://tromoi.com/uploads/static/phong_tro_hcm/Quan_12/379%20le%20thi%20rieng/379_le_thi_rieng_12.jpg',
        title: 'Căn hộ 789 Trần Duy Hưng, Cầu Giấy, Hà Nội',
        price: '12 triệu/tháng',
        type: 'Căn hộ',
        area: '85 m²',
        location: 'Cầu Giấy, Thành phố Hà Nội',
        isFavorite: true,
        isHot: true,
    },
    {
        id: 5,
        image: 'https://tromoi.com/uploads/static/phong_tro_hcm/Quan_12/379%20le%20thi%20rieng/379_le_thi_rieng_13.jpg',
        title: 'Nhà trọ 321 Kim Mã, Ba Đình, Hà Nội',
        price: '5,8 triệu/tháng',
        type: 'Nhà trọ, phòng trọ',
        area: '65 m²',
        location: 'Ba Đình, Thành phố Hà Nội',
        isFavorite: false,
        isHot: true,
    },
    {
        id: 6,
        image: 'https://tromoi.com/uploads/static/phong_tro_hcm/Quan_12/379%20le%20thi%20rieng/379_le_thi_rieng_14.jpg',
        title: 'Phòng trọ 654 Đường Láng, Đống Đa, Hà Nội',
        price: '2,8 triệu/tháng',
        type: 'Phòng trọ',
        area: '35 m²',
        location: 'Đống Đa, Thành phố Hà Nội',
        isFavorite: true,
        isHot: true,
    },
    {
        id: 7,
        image: 'https://tromoi.com/uploads/static/phong_tro_hcm/Quan_12/379%20le%20thi%20rieng/379_le_thi_rieng_10.jpg',
        title: 'Nhà nguyên căn 987 Giải Phóng, Hai Bà Trưng, Hà Nội',
        price: '15 triệu/tháng',
        type: 'Nhà nguyên căn',
        area: '150 m²',
        location: 'Hai Bà Trưng, Thành phố Hà Nội',
        isFavorite: false,
        isHot: true,
    },
    {
        id: 8,
        image: 'https://tromoi.com/uploads/static/phong_tro_hcm/Quan_12/379%20le%20thi%20rieng/379_le_thi_rieng_11.jpg',
        title: 'Căn hộ 147 Tôn Đức Thắng, Đống Đa, Hà Nội',
        price: '18 triệu/tháng',
        type: 'Căn hộ',
        area: '110 m²',
        location: 'Đống Đa, Thành phố Hà Nội',
        isFavorite: true,
        isHot: true,
    },
    {
        id: 9,
        image: 'https://tromoi.com/uploads/static/phong_tro_hcm/Quan_12/379%20le%20thi%20rieng/379_le_thi_rieng_11.jpg',
        title: 'Nhà trọ 258 Lê Duẩn, Hoàn Kiếm, Hà Nội',
        price: '6,5 triệu/tháng',
        type: 'Nhà trọ, phòng trọ',
        area: '75 m²',
        location: 'Hoàn Kiếm, Thành phố Hà Nội',
        isFavorite: false,
        isHot: true,
    },
    {
        id: 10,
        image: 'https://tromoi.com/uploads/static/phong_tro_hcm/Quan_12/379%20le%20thi%20rieng/379_le_thi_rieng_11.jpg',
        title: 'Phòng trọ 369 Phố Huế, Hai Bà Trưng, Hà Nội',
        price: '4,2 triệu/tháng',
        type: 'Phòng trọ',
        area: '50 m²',
        location: 'Hai Bà Trưng, Thành phố Hà Nội',
        isFavorite: true,
        isHot: true,
    },
    {
        id: 11,
        image: 'https://tromoi.com/uploads/static/phong_tro_hcm/Quan_12/379%20le%20thi%20rieng/379_le_thi_rieng_9.jpg',
        title: 'Nhà trọ 159 Nguyễn Trãi, Thanh Xuân, Hà Nội',
        price: '3,8 triệu/tháng',
        type: 'Nhà trọ, phòng trọ',
        area: '55 m²',
        location: 'Thanh Xuân, Thành phố Hà Nội',
        isFavorite: false,
        isHot: true,
    },
    {
        id: 12,
        image: 'https://tromoi.com/uploads/static/phong_tro_hcm/Quan_12/379%20le%20thi%20rieng/379_le_thi_rieng_10.jpg',
        title: 'Căn hộ 456 Hoàng Quốc Việt, Cầu Giấy, Hà Nội',
        price: '14 triệu/tháng',
        type: 'Căn hộ',
        area: '95 m²',
        location: 'Cầu Giấy, Thành phố Hà Nội',
        isFavorite: true,
        isHot: true,
    },
    {
        id: 13,
        image: 'https://tromoi.com/uploads/static/phong_tro_hcm/Quan_12/379%20le%20thi%20rieng/379_le_thi_rieng_11.jpg',
        title: 'Phòng trọ 789 Láng Hạ, Đống Đa, Hà Nội',
        price: '3,5 triệu/tháng',
        type: 'Phòng trọ',
        area: '40 m²',
        location: 'Đống Đa, Thành phố Hà Nội',
        isFavorite: false,
        isHot: true,
    },
    {
        id: 14,
        image: 'https://tromoi.com/uploads/static/phong_tro_hcm/Quan_12/379%20le%20thi%20rieng/379_le_thi_rieng_12.jpg',
        title: 'Nhà nguyên căn 321 Trường Chinh, Thanh Xuân, Hà Nội',
        price: '22 triệu/tháng',
        type: 'Nhà nguyên căn',
        area: '180 m²',
        location: 'Thanh Xuân, Thành phố Hà Nội',
        isFavorite: true,
        isHot: true,
    },
    {
        id: 15,
        image: 'https://tromoi.com/uploads/static/phong_tro_hcm/Quan_12/379%20le%20thi%20rieng/379_le_thi_rieng_13.jpg',
        title: 'Nhà trọ 654 Giải Phóng, Hoàng Mai, Hà Nội',
        price: '4,8 triệu/tháng',
        type: 'Nhà trọ, phòng trọ',
        area: '70 m²',
        location: 'Hoàng Mai, Thành phố Hà Nội',
        isFavorite: false,
        isHot: true,
    },
    {
        id: 16,
        image: 'https://tromoi.com/uploads/static/phong_tro_hcm/Quan_12/379%20le%20thi%20rieng/379_le_thi_rieng_14.jpg',
        title: 'Căn hộ 987 Lê Duẩn, Hoàn Kiếm, Hà Nội',
        price: '16 triệu/tháng',
        type: 'Căn hộ',
        area: '105 m²',
        location: 'Hoàn Kiếm, Thành phố Hà Nội',
        isFavorite: true,
        isHot: true,
    },
    {
        id: 17,
        image: 'https://tromoi.com/uploads/static/phong_tro_hcm/Quan_6/633.12.29/z7062867437260_d542a06ebb7005ab39627bf808a703c4.jpg',
        title: 'Phòng trọ 147 Kim Mã, Ba Đình, Hà Nội',
        price: '5,2 triệu/tháng',
        type: 'Phòng trọ',
        area: '60 m²',
        location: 'Ba Đình, Thành phố Hà Nội',
        isFavorite: false,
        isHot: true,
    },
    {
        id: 18,
        image: 'https://tromoi.com/uploads/static/phong_tro_hcm/Quan_7/76.18_HuynhTanPhat/photo_10_2025_09_05_10_19_50.jpg',
        title: 'Nhà nguyên căn 258 Tôn Đức Thắng, Đống Đa, Hà Nội',
        price: '19 triệu/tháng',
        type: 'Nhà nguyên căn',
        area: '160 m²',
        location: 'Đống Đa, Thành phố Hà Nội',
        isFavorite: true,
        isHot: true,
    },
    {
        id: 19,
        image: 'https://tromoi.com/uploads/static/phong_tro_hcm/Quan_11/153%20tran%20quy/z7062867416575_0c94e2e39cd2e24da6086d569562a98a.jpg',
        title: 'Nhà trọ 369 Phố Huế, Hai Bà Trưng, Hà Nội',
        price: '4,0 triệu/tháng',
        type: 'Nhà trọ, phòng trọ',
        area: '48 m²',
        location: 'Hai Bà Trưng, Thành phố Hà Nội',
        isFavorite: false,
        isHot: true,
    },
    {
        id: 20,
        image: 'https://tromoi.com/uploads/static/phong_tro_hcm/Quan_4/170-32/z7042421162070_b469cee4cae336fcf7dc48ab8028ff26.jpg',
        title: 'Căn hộ 741 Láng Thượng, Đống Đa, Hà Nội',
        price: '13 triệu/tháng',
        type: 'Căn hộ',
        area: '88 m²',
        location: 'Đống Đa, Thành phố Hà Nội',
        isFavorite: true,
        isHot: true,
    },
    {
        id: 21,
        image: 'https://tromoi.com/uploads/static/phong_tro_hcm/Quan_12/379%20le%20thi%20rieng/379_le_thi_rieng_9.jpg',
        title: 'Phòng trọ 852 Đống Đa, Đống Đa, Hà Nội',
        price: '3,0 triệu/tháng',
        type: 'Phòng trọ',
        area: '38 m²',
        location: 'Đống Đa, Thành phố Hà Nội',
        isFavorite: false,
        isHot: true,
    },
    {
        id: 22,
        image: 'https://tromoi.com/uploads/static/phong_tro_hcm/Quan_12/379%20le%20thi%20rieng/379_le_thi_rieng_10.jpg',
        title: 'Nhà trọ 963 Cầu Giấy, Cầu Giấy, Hà Nội',
        price: '6,8 triệu/tháng',
        type: 'Nhà trọ, phòng trọ',
        area: '80 m²',
        location: 'Cầu Giấy, Thành phố Hà Nội',
        isFavorite: true,
        isHot: true,
    },
    {
        id: 23,
        image: 'https://tromoi.com/uploads/static/phong_tro_hcm/Quan_12/379%20le%20thi%20rieng/379_le_thi_rieng_11.jpg',
        title: 'Nhà nguyên căn 174 Thanh Xuân, Thanh Xuân, Hà Nội',
        price: '25 triệu/tháng',
        type: 'Nhà nguyên căn',
        area: '200 m²',
        location: 'Thanh Xuân, Thành phố Hà Nội',
        isFavorite: false,
        isHot: true,
    },
    {
        id: 24,
        image: 'https://tromoi.com/uploads/static/phong_tro_hcm/Quan_12/379%20le%20thi%20rieng/379_le_thi_rieng_12.jpg',
        title: 'Căn hộ 285 Long Biên, Long Biên, Hà Nội',
        price: '11 triệu/tháng',
        type: 'Căn hộ',
        area: '92 m²',
        location: 'Long Biên, Thành phố Hà Nội',
        isFavorite: true,
        isHot: true,
    },
    {
        id: 25,
        image: 'https://tromoi.com/uploads/static/phong_tro_hcm/Quan_12/379%20le%20thi%20rieng/379_le_thi_rieng_13.jpg',
        title: 'Phòng trọ 396 Hoàng Mai, Hoàng Mai, Hà Nội',
        price: '3,3 triệu/tháng',
        type: 'Phòng trọ',
        area: '42 m²',
        location: 'Hoàng Mai, Thành phố Hà Nội',
        isFavorite: false,
        isHot: true,
    },
];

export {
    banner,
    ads1,
    ads2,
    ads3,
    ads4,
    ads5,
    hot,
    banner_ohdidi,
    badinh_img,
    dongda_img,
    tayho_img,
    thanhxuan_img,
    tuliem_img,
    longbien_img,
    banner_user,
    logo,
    bg_auth,
    img_auth,
    coin,
    admin_logo,
    mail,
    mess,
    phone,
    zalo,
};
